app:
#  image: 34781655cf03
  build: ./php-fpm
  expose:
    - "9000"
  volumes:
    - /var/www/yii2/advanced:/var/www/html/
#    - ./apache/conf/sites-enabled/:/etc/apache2/sites-enabled/
  links:
    - db
  restart: always

nginx:
    build: ./nginx
#    image: 7ac8cd6e35d7
    ports:
        - "8080:80"
    links:
        - app
    volumes_from:
        - app
    restart: always

db:
  image: mysql:latest
  ports:
    - "3306:3306"
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: dbtest
    MYSQL_USER: dbuser
    MYSQL_PASSWORD: asdf
  restart: always